packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@netlify/functions": ^5.3.0
  "@tanstack/react-router": ^1.170.17
  "@tanstack/router-devtools": ^1.167.0
  "@tanstack/router-plugin": ^1.168.19
  "@types/node": ^24
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.3
  react: ^19.2.7
  react-dom: ^19.2.7
  tailwindcss: ^4.3.2
  typescript: ^6
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4

catalogMode: prefer

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
