/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppWalletsIndexRouteImport } from './routes/_app/wallets/index'
import { Route as AppWalletsWalletIdIndexRouteImport } from './routes/_app/wallets/$walletId/index'
import { Route as AppWalletsWalletIdSettingsRouteImport } from './routes/_app/wallets/$walletId/settings'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWalletsIndexRoute = AppWalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWalletsWalletIdIndexRoute = AppWalletsWalletIdIndexRouteImport.update({
  id: '/wallets/$walletId/',
  path: '/wallets/$walletId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWalletsWalletIdSettingsRoute =
  AppWalletsWalletIdSettingsRouteImport.update({
    id: '/wallets/$walletId/settings',
    path: '/wallets/$walletId/settings',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/wallets/': typeof AppWalletsIndexRoute
  '/wallets/$walletId/settings': typeof AppWalletsWalletIdSettingsRoute
  '/wallets/$walletId/': typeof AppWalletsWalletIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/wallets': typeof AppWalletsIndexRoute
  '/wallets/$walletId/settings': typeof AppWalletsWalletIdSettingsRoute
  '/wallets/$walletId': typeof AppWalletsWalletIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/wallets/': typeof AppWalletsIndexRoute
  '/_app/wallets/$walletId/settings': typeof AppWalletsWalletIdSettingsRoute
  '/_app/wallets/$walletId/': typeof AppWalletsWalletIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/auth/'
    | '/wallets/'
    | '/wallets/$walletId/settings'
    | '/wallets/$walletId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/auth'
    | '/wallets'
    | '/wallets/$walletId/settings'
    | '/wallets/$walletId'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/_app/'
    | '/auth/'
    | '/_app/wallets/'
    | '/_app/wallets/$walletId/settings'
    | '/_app/wallets/$walletId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/wallets/': {
      id: '/_app/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof AppWalletsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/wallets/$walletId/': {
      id: '/_app/wallets/$walletId/'
      path: '/wallets/$walletId'
      fullPath: '/wallets/$walletId/'
      preLoaderRoute: typeof AppWalletsWalletIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/wallets/$walletId/settings': {
      id: '/_app/wallets/$walletId/settings'
      path: '/wallets/$walletId/settings'
      fullPath: '/wallets/$walletId/settings'
      preLoaderRoute: typeof AppWalletsWalletIdSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppWalletsIndexRoute: typeof AppWalletsIndexRoute
  AppWalletsWalletIdSettingsRoute: typeof AppWalletsWalletIdSettingsRoute
  AppWalletsWalletIdIndexRoute: typeof AppWalletsWalletIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppWalletsIndexRoute: AppWalletsIndexRoute,
  AppWalletsWalletIdSettingsRoute: AppWalletsWalletIdSettingsRoute,
  AppWalletsWalletIdIndexRoute: AppWalletsWalletIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
