/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as StatementTokenRouteImport } from './routes/statement/$token'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppWalletsIndexRouteImport } from './routes/_app/wallets/index'
import { Route as AppWalletsWalletIdRouteRouteImport } from './routes/_app/wallets/$walletId/route'
import { Route as AppWalletsWalletIdIndexRouteImport } from './routes/_app/wallets/$walletId/index'
import { Route as AppWalletsWalletIdSettingsIndexRouteImport } from './routes/_app/wallets/$walletId/settings/index'
import { Route as AppWalletsWalletIdSettingsStatementSharesRouteImport } from './routes/_app/wallets/$walletId/settings/statement-shares'
import { Route as AppWalletsWalletIdSettingsMembersRouteImport } from './routes/_app/wallets/$walletId/settings/members'
import { Route as AppWalletsWalletIdSettingsGeneralRouteImport } from './routes/_app/wallets/$walletId/settings/general'
import { Route as AppWalletsWalletIdSettingsActivityRouteImport } from './routes/_app/wallets/$walletId/settings/activity'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const StatementTokenRoute = StatementTokenRouteImport.update({
  id: '/statement/$token',
  path: '/statement/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWalletsIndexRoute = AppWalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWalletsWalletIdRouteRoute = AppWalletsWalletIdRouteRouteImport.update({
  id: '/wallets/$walletId',
  path: '/wallets/$walletId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWalletsWalletIdIndexRoute = AppWalletsWalletIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWalletsWalletIdRouteRoute,
} as any)
const AppWalletsWalletIdSettingsIndexRoute =
  AppWalletsWalletIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppWalletsWalletIdRouteRoute,
  } as any)
const AppWalletsWalletIdSettingsStatementSharesRoute =
  AppWalletsWalletIdSettingsStatementSharesRouteImport.update({
    id: '/settings/statement-shares',
    path: '/settings/statement-shares',
    getParentRoute: () => AppWalletsWalletIdRouteRoute,
  } as any)
const AppWalletsWalletIdSettingsMembersRoute =
  AppWalletsWalletIdSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AppWalletsWalletIdRouteRoute,
  } as any)
const AppWalletsWalletIdSettingsGeneralRoute =
  AppWalletsWalletIdSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AppWalletsWalletIdRouteRoute,
  } as any)
const AppWalletsWalletIdSettingsActivityRoute =
  AppWalletsWalletIdSettingsActivityRouteImport.update({
    id: '/settings/activity',
    path: '/settings/activity',
    getParentRoute: () => AppWalletsWalletIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/statement/$token': typeof StatementTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/wallets/$walletId': typeof AppWalletsWalletIdRouteRouteWithChildren
  '/wallets/': typeof AppWalletsIndexRoute
  '/wallets/$walletId/': typeof AppWalletsWalletIdIndexRoute
  '/wallets/$walletId/settings/activity': typeof AppWalletsWalletIdSettingsActivityRoute
  '/wallets/$walletId/settings/general': typeof AppWalletsWalletIdSettingsGeneralRoute
  '/wallets/$walletId/settings/members': typeof AppWalletsWalletIdSettingsMembersRoute
  '/wallets/$walletId/settings/statement-shares': typeof AppWalletsWalletIdSettingsStatementSharesRoute
  '/wallets/$walletId/settings/': typeof AppWalletsWalletIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/statement/$token': typeof StatementTokenRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/wallets': typeof AppWalletsIndexRoute
  '/wallets/$walletId': typeof AppWalletsWalletIdIndexRoute
  '/wallets/$walletId/settings/activity': typeof AppWalletsWalletIdSettingsActivityRoute
  '/wallets/$walletId/settings/general': typeof AppWalletsWalletIdSettingsGeneralRoute
  '/wallets/$walletId/settings/members': typeof AppWalletsWalletIdSettingsMembersRoute
  '/wallets/$walletId/settings/statement-shares': typeof AppWalletsWalletIdSettingsStatementSharesRoute
  '/wallets/$walletId/settings': typeof AppWalletsWalletIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/statement/$token': typeof StatementTokenRoute
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/wallets/$walletId': typeof AppWalletsWalletIdRouteRouteWithChildren
  '/_app/wallets/': typeof AppWalletsIndexRoute
  '/_app/wallets/$walletId/': typeof AppWalletsWalletIdIndexRoute
  '/_app/wallets/$walletId/settings/activity': typeof AppWalletsWalletIdSettingsActivityRoute
  '/_app/wallets/$walletId/settings/general': typeof AppWalletsWalletIdSettingsGeneralRoute
  '/_app/wallets/$walletId/settings/members': typeof AppWalletsWalletIdSettingsMembersRoute
  '/_app/wallets/$walletId/settings/statement-shares': typeof AppWalletsWalletIdSettingsStatementSharesRoute
  '/_app/wallets/$walletId/settings/': typeof AppWalletsWalletIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/statement/$token'
    | '/auth/'
    | '/wallets/$walletId'
    | '/wallets/'
    | '/wallets/$walletId/'
    | '/wallets/$walletId/settings/activity'
    | '/wallets/$walletId/settings/general'
    | '/wallets/$walletId/settings/members'
    | '/wallets/$walletId/settings/statement-shares'
    | '/wallets/$walletId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/statement/$token'
    | '/'
    | '/auth'
    | '/wallets'
    | '/wallets/$walletId'
    | '/wallets/$walletId/settings/activity'
    | '/wallets/$walletId/settings/general'
    | '/wallets/$walletId/settings/members'
    | '/wallets/$walletId/settings/statement-shares'
    | '/wallets/$walletId/settings'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/statement/$token'
    | '/_app/'
    | '/auth/'
    | '/_app/wallets/$walletId'
    | '/_app/wallets/'
    | '/_app/wallets/$walletId/'
    | '/_app/wallets/$walletId/settings/activity'
    | '/_app/wallets/$walletId/settings/general'
    | '/_app/wallets/$walletId/settings/members'
    | '/_app/wallets/$walletId/settings/statement-shares'
    | '/_app/wallets/$walletId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  StatementTokenRoute: typeof StatementTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/statement/$token': {
      id: '/statement/$token'
      path: '/statement/$token'
      fullPath: '/statement/$token'
      preLoaderRoute: typeof StatementTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/wallets/': {
      id: '/_app/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof AppWalletsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/wallets/$walletId': {
      id: '/_app/wallets/$walletId'
      path: '/wallets/$walletId'
      fullPath: '/wallets/$walletId'
      preLoaderRoute: typeof AppWalletsWalletIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/wallets/$walletId/': {
      id: '/_app/wallets/$walletId/'
      path: '/'
      fullPath: '/wallets/$walletId/'
      preLoaderRoute: typeof AppWalletsWalletIdIndexRouteImport
      parentRoute: typeof AppWalletsWalletIdRouteRoute
    }
    '/_app/wallets/$walletId/settings/': {
      id: '/_app/wallets/$walletId/settings/'
      path: '/settings'
      fullPath: '/wallets/$walletId/settings/'
      preLoaderRoute: typeof AppWalletsWalletIdSettingsIndexRouteImport
      parentRoute: typeof AppWalletsWalletIdRouteRoute
    }
    '/_app/wallets/$walletId/settings/statement-shares': {
      id: '/_app/wallets/$walletId/settings/statement-shares'
      path: '/settings/statement-shares'
      fullPath: '/wallets/$walletId/settings/statement-shares'
      preLoaderRoute: typeof AppWalletsWalletIdSettingsStatementSharesRouteImport
      parentRoute: typeof AppWalletsWalletIdRouteRoute
    }
    '/_app/wallets/$walletId/settings/members': {
      id: '/_app/wallets/$walletId/settings/members'
      path: '/settings/members'
      fullPath: '/wallets/$walletId/settings/members'
      preLoaderRoute: typeof AppWalletsWalletIdSettingsMembersRouteImport
      parentRoute: typeof AppWalletsWalletIdRouteRoute
    }
    '/_app/wallets/$walletId/settings/general': {
      id: '/_app/wallets/$walletId/settings/general'
      path: '/settings/general'
      fullPath: '/wallets/$walletId/settings/general'
      preLoaderRoute: typeof AppWalletsWalletIdSettingsGeneralRouteImport
      parentRoute: typeof AppWalletsWalletIdRouteRoute
    }
    '/_app/wallets/$walletId/settings/activity': {
      id: '/_app/wallets/$walletId/settings/activity'
      path: '/settings/activity'
      fullPath: '/wallets/$walletId/settings/activity'
      preLoaderRoute: typeof AppWalletsWalletIdSettingsActivityRouteImport
      parentRoute: typeof AppWalletsWalletIdRouteRoute
    }
  }
}

interface AppWalletsWalletIdRouteRouteChildren {
  AppWalletsWalletIdIndexRoute: typeof AppWalletsWalletIdIndexRoute
  AppWalletsWalletIdSettingsActivityRoute: typeof AppWalletsWalletIdSettingsActivityRoute
  AppWalletsWalletIdSettingsGeneralRoute: typeof AppWalletsWalletIdSettingsGeneralRoute
  AppWalletsWalletIdSettingsMembersRoute: typeof AppWalletsWalletIdSettingsMembersRoute
  AppWalletsWalletIdSettingsStatementSharesRoute: typeof AppWalletsWalletIdSettingsStatementSharesRoute
  AppWalletsWalletIdSettingsIndexRoute: typeof AppWalletsWalletIdSettingsIndexRoute
}

const AppWalletsWalletIdRouteRouteChildren: AppWalletsWalletIdRouteRouteChildren =
  {
    AppWalletsWalletIdIndexRoute: AppWalletsWalletIdIndexRoute,
    AppWalletsWalletIdSettingsActivityRoute:
      AppWalletsWalletIdSettingsActivityRoute,
    AppWalletsWalletIdSettingsGeneralRoute:
      AppWalletsWalletIdSettingsGeneralRoute,
    AppWalletsWalletIdSettingsMembersRoute:
      AppWalletsWalletIdSettingsMembersRoute,
    AppWalletsWalletIdSettingsStatementSharesRoute:
      AppWalletsWalletIdSettingsStatementSharesRoute,
    AppWalletsWalletIdSettingsIndexRoute: AppWalletsWalletIdSettingsIndexRoute,
  }

const AppWalletsWalletIdRouteRouteWithChildren =
  AppWalletsWalletIdRouteRoute._addFileChildren(
    AppWalletsWalletIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppWalletsWalletIdRouteRoute: typeof AppWalletsWalletIdRouteRouteWithChildren
  AppWalletsIndexRoute: typeof AppWalletsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppWalletsWalletIdRouteRoute: AppWalletsWalletIdRouteRouteWithChildren,
  AppWalletsIndexRoute: AppWalletsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  StatementTokenRoute: StatementTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
